<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Http\File;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            // Papelaria
            [
            'name' => 'Chamex Multi',
            'quantity' => '50',
            'description' => 'Pacote Chamex Multi 200 unidades',
            'category' => 'papelaria',
            'price' => '10',
            'sale_price' => '14',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/chamex.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Chamex Carta',
            'quantity' => '40',
            'description' => 'Papel Carta Chamex 150 unidades',
            'category' => 'papelaria',
            'price' => '12',
            'sale_price' => '16',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/chamex-carta.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Chamex Colors',
            'quantity' => '60',
            'description' => 'Pacote Chamex Colors 100 unidades',
            'category' => 'papelaria',
            'price' => '14',
            'sale_price' => '18',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/chamex-colors.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Chamex Office',
            'quantity' => '70',
            'description' => 'Pacote Chamex Office 200 unidades',
            'category' => 'papelaria',
            'price' => '18',
            'sale_price' => '24',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/chamex-office.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Chamex Vai Brasil',
            'quantity' => '20',
            'description' => 'Chamex Edição Vai Brasil 200 unidades',
            'category' => 'papelaria',
            'price' => '25',
            'sale_price' => '36',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/chamex-vai-brasil.jpeg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Papel Vegetal Unidade',
            'quantity' => '800',
            'description' => 'Papel Vegetal',
            'category' => 'papelaria',
            'price' => '0.5',
            'sale_price' => '1.2',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/papel-vegetal.jpeg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Borracha Faber Castell',
            'quantity' => '300',
            'description' => 'Borracha Branca Faber Castell',
            'category' => 'papelaria',
            'price' => '0.1',
            'sale_price' => '0.3',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/borracha-fabercastell.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Canetas Coloridas Uni.',
            'quantity' => '300',
            'description' => 'Canetas Coloridas Unidade',
            'category' => 'papelaria',
            'price' => '1.5',
            'sale_price' => '2.5',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/canetas.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Lápis Pedra Papel Tesoura.',
            'quantity' => '40',
            'description' => 'Lápis Pedra Papel Tesoura Unidade',
            'category' => 'papelaria',
            'price' => '1',
            'sale_price' => '4',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/lapis-jokenpo.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Lápis Escolar Preto',
            'quantity' => '500',
            'description' => 'Lápis Escolar Preto',
            'category' => 'papelaria',
            'price' => '0.5',
            'sale_price' => '1.2',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/lapis-preto-escolar.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],

            // Escritório
            [
            'name' => 'Caneta Bic',
            'quantity' => '300',
            'description' => 'Caixa com 30 canetas Bic',
            'category' => 'escritorio',
            'price' => '30',
            'sale_price' => '45',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/caneta-bic.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Calculadora Casio',
            'quantity' => '20',
            'description' => 'Calculadora',
            'category' => 'escritorio',
            'price' => '8',
            'sale_price' => '16',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/calculadora-casio.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Grampeador',
            'quantity' => '15',
            'description' => 'Grampeador de papel',
            'category' => 'escritorio',
            'price' => '6',
            'sale_price' => '8',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/grampeador.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Grampeador Rosa',
            'quantity' => '12',
            'description' => 'Grampeador de papel, só que rosa ;)',
            'category' => 'escritorio',
            'price' => '7',
            'sale_price' => '9',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/grampeador-2.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Grampeador A17',
            'quantity' => '7',
            'description' => 'Grampeador A17',
            'category' => 'escritorio',
            'price' => '10',
            'sale_price' => '19',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/grampeador A17.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Grampeador Mini',
            'quantity' => '7',
            'description' => 'Grampeador para mãos pequenas',
            'category' => 'escritorio',
            'price' => '4',
            'sale_price' => '7',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/grampeador-mini.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Maleta Dello',
            'quantity' => '7',
            'description' => 'Maleta de qualidade, olha como é bonita!',
            'category' => 'escritorio',
            'price' => '30',
            'sale_price' => '60',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/maleta-dello.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],

            // Arte
            [ 
            'name' => 'Canetinhas Faber Castell',
            'quantity' => '50',
            'description' => 'Canetinhas Hidrográficas Coloridas',
            'category' => 'arte',
            'price' => '8',
            'sale_price' => '14',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/canetinhas-hidrograficas-fabercastell.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Giz de Cera Faber Castell',
            'quantity' => '50',
            'description' => 'Giz de Cera Faber Castell 16 uni.',
            'category' => 'arte',
            'price' => '6',
            'sale_price' => '12',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/giz-cera-fabercastell.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Lápis de Cor Faber Castell',
            'quantity' => '50',
            'description' => 'Lapis de Cor Faber Castell 26 uni.',
            'category' => 'arte',
            'price' => '9',
            'sale_price' => '18',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/lapis-faber-castel.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Lápis Multi Color',
            'quantity' => '70',
            'description' => 'Lápis Multi Color 26 uni.',
            'category' => 'arte',
            'price' => '7',
            'sale_price' => '14',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/lapis-multicolor.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Pincéis Misto',
            'quantity' => '30',
            'description' => 'Pincéis Mistos Unidade',
            'category' => 'arte',
            'price' => '2',
            'sale_price' => '7',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/pincel-misto.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Tinta Guache',
            'quantity' => '30',
            'description' => 'Tinta Guache 6 uni.',
            'category' => 'arte',
            'price' => '8',
            'sale_price' => '14',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/tinta-guache-6.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            [ 
            'name' => 'Tinta Guache Unidade',
            'quantity' => '30',
            'description' => 'Tinta Guache Unidade',
            'category' => 'arte',
            'price' => '2',
            'sale_price' => '5',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/tinta-guache-uni.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],    
            
            // Outros
            [ 
            'name' => 'Caneca',
            'quantity' => '10',
            'description' => 'Caneca personalizada Friends!',
            'category' => 'outros',
            'price' => '5',
            'sale_price' => '12',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/caneca-friends.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Estojo Académie',
            'quantity' => '10',
            'description' => 'Estojo Escolar Académie',
            'category' => 'outros',
            'price' => '8',
            'sale_price' => '10',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/estojo-escolar-academie.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Estojo Escolar divisórias',
            'quantity' => '10',
            'description' => 'Estojo Escolar c/ divisórias',
            'category' => 'outros',
            'price' => '12',
            'sale_price' => '18',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/estojo-escolar-divi.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Estojo Escolar',
            'quantity' => '25',
            'description' => 'Estojo Escolar',
            'category' => 'outros',
            'price' => '4',
            'sale_price' => '6',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/estojo-escolar.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Mochila Escolar Académie',
            'quantity' => '25',
            'description' => 'Mochila Preta',
            'category' => 'outros',
            'price' => '33',
            'sale_price' => '62',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/mochila-escolar-academie.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Mochila Escolar Juvenil',
            'quantity' => '25',
            'description' => 'Mochila Preta',
            'category' => 'outros',
            'price' => '35',
            'sale_price' => '67',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/mochila-escolar-juvenil.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Mochila Escolar Rosa',
            'quantity' => '25',
            'description' => 'Mochila Rosa',
            'category' => 'outros',
            'price' => '20',
            'sale_price' => '40',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/mochila-rosa.jpg')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [ 
            'name' => 'Caneca Preta',
            'quantity' => '60',
            'description' => 'Caneca Preta Personalizada',
            'category' => 'outros',
            'price' => '8',
            'sale_price' => '18',
            'photo' => Storage::disk('s3')->putFile('products', new File('storage/app/public/imagens/caneca_preta_personalizada.png')),
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
    }
}